on:
  push:
    branches:
      - main
name: build gatsby
jobs:
  build_gatsby:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14.15.0'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - uses: peaceiris/actions-gh-pages@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          PUBLISH_BRANCH: deployment
          PUBLISH_DIR: ./public